### ISSUE TITLE
use symbolic icons

### ISSUE THREAD

**Issue by bilelmoussaoui** [lucasdiedrich/gnome-display-switcher#10]
Symbolic icons can be themed and recolored using CSS 
![capture du 2016-05-17 15-51-46](https://cloud.githubusercontent.com/assets/7660997/15324564/4921a608-1c47-11e6-9252-a494cfa29dc7.png)

**Comment by lucasdiedrich** [comment]
With initial tests, using @theme_fg_color the text doesn't align center... Going to make some improvements first.

![image](https://cloud.githubusercontent.com/assets/817482/16026304/d6fdad2a-31a3-11e6-8387-21ec81c190ff.png)

**Comment by bil-elmoussaoui** [comment]
Well @theme_fg_color is more for the text color, i can help you centering the text if you want ? :) You just need to put the text + icon on a vertical box and enable fill, disable expand

**Comment by lucasdiedrich** [comment]
Ok, this looks promising, going to test that way. Also, i will try to use the @theme_fg_color for the svg icons...

**Comment by lucasdiedrich** [comment]
After some research and with the help of gnome's irc (#newcomers), it is not possible to use variable colors with Gnome Extension Stylesheets. The use is for GTK Themes only, not Gnome Shell Themes, I'm thinking about closing this thread for now.

This strange behavior explains why the text-align is not working when i set the color: @theme_fg_color;

**Comment by bil-elmoussaoui** [comment]
@lucasdiedrich How it's not possible when it works??

**Comment by lucasdiedrich** [comment]
Well, it doesn't, its not possible because there is no support for that feature in Gnome's Shell Theme, and if the problem happens to me is most probably that this gonna happen with other users.

But, check this out, this can explain why its working, i've tested with three configurations with default theme (adwaita) and numix:

1. **Using color: white;**
![image](https://cloud.githubusercontent.com/assets/817482/16064112/cc66ba56-3274-11e6-8c28-4336e211dd7b.png)
![image](https://cloud.githubusercontent.com/assets/817482/16064147/0a914314-3275-11e6-817c-31a77d4aa0cd.png)

See that both **background-color**, **text-align** and **color** works...

2.  **Using: @theme_fg_color**
![image](https://cloud.githubusercontent.com/assets/817482/16064205/6707300e-3275-11e6-9011-b077250e656f.png)

See that not only the attributes **background-color**, **text-align** and **color** are not correct, but also it didn't even loaded the numix theme, the print screen should be from a Numix loaded theme. Using @theme_fg_color breaks the extension stylesheets.

3. **Not setting the color** 
![image](https://cloud.githubusercontent.com/assets/817482/16064285/2247ec96-3276-11e6-8c7d-83f341f79ed8.png)
![image](https://cloud.githubusercontent.com/assets/817482/16064304/430cd2f2-3276-11e6-8057-23fe3e8e15ea.png)

Not setting the color not only make everything as expected, but also, load the default color from the theme. I think this is the best aproach.

**Comment by bil-elmoussaoui** [comment]
Well i didn't knew that! Thanks for the info, that explains why gnome-shell theme does not change the color when you apply the dark theme

**Comment by lucasdiedrich** [comment]
Unfortunately, because of that i can not even fill the svg with different colors. It seems that the stylesheet only works for overding the default css.

Anyway, going to remove the definition of color from the stylesheet which fix the issue, and than close it.

Thanks for the help @bil-elmoussaoui.

**Comment by lucasdiedrich** [comment]
This extension will be disabled since this functionalty is available at Gnome 3.26+. To use Gnome just press 'Super' + P and hold Super.
