### ISSUE TITLE
Position of secondary display

### ISSUE THREAD

**Issue by satriani-vai** [lucasdiedrich/gnome-display-switcher#3]
I use my one klick script
`xrandr --output $sec_disp --right-of $prim_disp --auto`
The thing is to position the secondary display to the right side of the primary display.
It would be nice to put this option.

**Comment by phocean** [comment]
This extension is great, but it would be even better if we could personalize positions.
I myself often use a "top of primary" setting so I cannot really use this extension as-is.

**Comment by lucasdiedrich** [comment]
Alex, there is an hidden feature on extended mode, if you select twice, it
will cycle between left and right.

Thanks.

Em sex, 29 de jan de 2016 9:30 PM, Alex <notifications@github.com> escreveu:

**Comment by lucasdiedrich** [comment]
Phocean, I'm gonna to add an TODO, Enhance Extended mode capability.

Thanks for this contribution.

Em sáb, 30 de jan de 2016 8:19 AM, phocean <notifications@github.com>
escreveu:

**Comment by lucasdiedrich** [comment]
## Advanced Extended Mode:  
1 - If you select twice "Extended" it will cycle between Left And Right Mode. 
2 - With "Extended" selected, press Top or Down to extend it to Above ou Below primary display.

Aprove pending over [EGO](https://extensions.gnome.org/review/5591).

**Comment by phocean** [comment]
Thanks a lot for this quick enhancement, it is wonderful !

**Comment by shihrer** [comment]
Is it possible to have a setting for the default position?  I like to shut off my secondary monitor and run a different computer on it from time to time.  The secondary monitor is to the right, so I have to extend twice.  This is a tad annoying and wastes a bit of time waiting for the monitors to come back on.

It'd be better if we can change it so it defaults to extend right rather than extend left.
